// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Deliveries string
	Districts  string
	Provinces  string
	Wards      string
}{
	Deliveries: "deliveries",
	Districts:  "districts",
	Provinces:  "provinces",
	Wards:      "wards",
}
